### ISSUE TITLE
/updateProfile issue

### ISSUE THREAD

**Issue by meryadri** [bayazitbora/ECE496-Capstone-Project#14]
The user is allowed to create a course profile without the course being properly inputted, as shown below: 
![image](https://github.com/user-attachments/assets/c1d880d5-583d-4331-9e71-b76ce8283388)

![image](https://github.com/user-attachments/assets/aeb3e040-0a5f-4f30-be74-b8fec7d8786c)

![image](https://github.com/user-attachments/assets/2a82ba83-37bf-4df5-a964-d14ecacd5a07)

**Comment by jbotpoint** [comment]
Thanks for pointing this out.
Fix should be adding an if statement in updateProfile
Will need to do for other fields too but will be along the following lines:

line 198 in views.py

```
if request.data['profile']['courseCode']:
 return Response({"message": "request did not contain courseCode"}, 
                        status=status.HTTP_400_BAD_REQUEST)

```
